name: frontend
on:
  push:
    branches:
      - staging

jobs:
  # unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - run: npm install
      - run: npm run build
      - run: npm test -- --coverage

  # build-and-push-image
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set image tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=production" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=staging" >> $GITHUB_ENV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${IMAGE_TAG}

  #Deployment to server
  deploy:
    runs-on: [self-hosted, linux, x64, frontend]
    needs: build
    steps:
      - name: deploy environment
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
            echo "IMAGE_TAG=production" >> $GITHUB_ENV
            echo "OVERRIDE_FILE=deployments/production/docker-compose.override.yml" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "IMAGE_TAG=staging" >> $GITHUB_ENV
            echo "OVERRIDE_FILE=deployments/staging/docker-compose.override.yml" >> $GITHUB_ENV
          fi
      - name: ENV_FILE
        run: |
          if [[ "$DEPLOY_ENV" == "production" ]]; then
            echo "${{ secrets.ENV_PRODUCTION }}" > .env
          else
            echo "${{ secrets.ENV_STAGING }}" > .env
          fi
          echo "âœ… Generated .env for $DEPLOY_ENV"

      - name: Deploy with Docker Compose
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          OVERRIDE_FILE: ${{ env.OVERRIDE_FILE }}
        run: |
          docker compose -f docker-compose.yml -f ${OVERRIDE_FILE} pull
          docker compose -f docker-compose.yml -f ${OVERRIDE_FILE} up -d --force-recreate --remove-orphans
          docker image prune -af --filter "until=24h"
          docker volume prune -f
          